INSERT INTO `empresas` VALUES (1, 'IFSC');
INSERT INTO `empresas` VALUES (2, 'UFSC');
INSERT INTO `empresas` VALUES (3, 'UDESC');
INSERT INTO `empresas` VALUES (4, 'Unisul');
INSERT INTO `empresas` VALUES (5, 'Viacredi');
INSERT INTO `empresas` VALUES (6, 'Intelbras');
INSERT INTO `empresas` VALUES (7, 'Univali');
INSERT INTO `empresas` VALUES (8, 'Clamed');
INSERT INTO `empresas` VALUES (9, 'Celulose Irani SC');
INSERT INTO `empresas` VALUES (10, 'Karsten');
INSERT INTO `empresas` VALUES (11, 'Krona Tubos e Conexões S/A');
INSERT INTO `empresas` VALUES (12, 'Studio Z');
INSERT INTO `empresas` VALUES (13, 'Softplan');
INSERT INTO `empresas` VALUES (14, 'Brandili Têxtil');
INSERT INTO `empresas` VALUES (15, 'Resultados Digitais');
INSERT INTO `empresas` VALUES (16, 'BN Papel Catarinense Ltda');
INSERT INTO `empresas` VALUES (17, 'Pollux');
INSERT INTO `empresas` VALUES (18, 'AGPR5');
INSERT INTO `empresas` VALUES (19, 'Multilog');
INSERT INTO `empresas` VALUES (20, 'Teltec Solutions');
INSERT INTO `empresas` VALUES (21, 'Ibadgy');
INSERT INTO `empresas` VALUES (22, 'HBSIS');
INSERT INTO `empresas` VALUES (23, 'Neoway');
INSERT INTO `empresas` VALUES (24, 'Better Comércio de Alimentos');
INSERT INTO `empresas` VALUES (25, 'Costa Rica Malhas e Confecções Ltda');
INSERT INTO `empresas` VALUES (26, 'Dental Cremer');
INSERT INTO `empresas` VALUES (27, 'Ogochi Menswear');
INSERT INTO `empresas` VALUES (28, 'Ufo Way Denim Brasil');
INSERT INTO `empresas` VALUES (29, 'Liplast Indústria e Comércio de Plástico Ltda');
INSERT INTO `empresas` VALUES (30, 'Têxtil Renauxview S/A');
INSERT INTO `empresas` VALUES (31, 'Exact Sales');
INSERT INTO `empresas` VALUES (32, 'Locativa Empreendimentos Imobiliários LTDA');
INSERT INTO `empresas` VALUES (33, 'Orion');
INSERT INTO `empresas` VALUES (34, 'Imaginarium');
INSERT INTO `empresas` VALUES (35, 'Involves');
INSERT INTO `empresas` VALUES (36, 'Valorem');
INSERT INTO `empresas` VALUES (37, 'Way2 Tecnologia');
INSERT INTO `empresas` VALUES (38, 'Cheesecake Labs');
INSERT INTO `empresas` VALUES (39, 'Embracon SC');
INSERT INTO `empresas` VALUES (40, 'Aurum Software');
INSERT INTO `empresas` VALUES (41, 'Dimensão Ind. do Vestuário');
INSERT INTO `empresas` VALUES (42, 'SBTUR - Viagens e Turismo S.A');
INSERT INTO `empresas` VALUES (43, 'Meu Móvel de Madeira');
INSERT INTO `empresas` VALUES (44, 'Inventti Tecnologia e Gestão');
